"""plugin toggles and modification logging

Revision ID: 246f8a09693d
Revises: a0b994911912
Create Date: 2026-06-08 01:17:06.013175

"""
# ruff: noqa: E501  # autogenerated migration lines exceed length limit
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '246f8a09693d'
down_revision: str | Sequence[str] | None = 'a0b994911912'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plugin_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plugin_name', name='uq_plugin_config_user_plugin')
    )
    op.create_index(op.f('ix_plugin_config_user_id'), 'plugin_config', ['user_id'], unique=False)
    op.create_table('plugin_config_conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('plugin_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conversation_id', 'plugin_name', name='uq_plugin_config_conv_user_conv_plugin')
    )
    op.create_index(op.f('ix_plugin_config_conversation_conversation_id'), 'plugin_config_conversation', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_plugin_config_conversation_user_id'), 'plugin_config_conversation', ['user_id'], unique=False)
    op.create_table('message_modifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('log_entry_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plugin_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('message_index', sa.Integer(), nullable=True),
    sa.Column('message_role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_modifications_entry', 'message_modifications', ['log_entry_id'], unique=False)
    op.create_index('ix_message_modifications_user_created', 'message_modifications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_modifications_user_created', table_name='message_modifications')
    op.drop_index('ix_message_modifications_entry', table_name='message_modifications')
    op.drop_table('message_modifications')
    op.drop_index(op.f('ix_plugin_config_conversation_user_id'), table_name='plugin_config_conversation')
    op.drop_index(op.f('ix_plugin_config_conversation_conversation_id'), table_name='plugin_config_conversation')
    op.drop_table('plugin_config_conversation')
    op.drop_index(op.f('ix_plugin_config_user_id'), table_name='plugin_config')
    op.drop_table('plugin_config')
    # ### end Alembic commands ###
