"""add message_diffs table for request interception diffs

Revision ID: dbdddb6fd90c
Revises: daa5a3a21cef
Create Date: 2026-06-08 05:00:09.974697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbdddb6fd90c'
down_revision: Union[str, Sequence[str], None] = 'daa5a3a21cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_diffs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('log_entry_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message_index', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('change_kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('original_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('modified_by', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_diffs_entry', 'message_diffs', ['log_entry_id'], unique=False)
    op.create_index('ix_message_diffs_user_created', 'message_diffs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_log_entries_user_chain_prefix'), 'log_entries', ['user_id', 'chain_prefix_key'], unique=False, postgresql_where='(chain_prefix_key IS NOT NULL)')
    op.create_index(op.f('ix_log_entries_user_chain_key'), 'log_entries', ['user_id', 'chain_key'], unique=False, postgresql_where='(chain_key IS NOT NULL)')
    op.drop_table('message_diffs')
    # ### end Alembic commands ###
